### ISSUE TITLE
Support for "exchangeInformation" endpoint

### ISSUE THREAD

**Issue by jangaraev** [wilianmaique/-php-mexc-api-v3#1]
Could you please implement a support for _exchangeInformation_ endpoint?

https://mexcdevelop.github.io/apidocs/spot_v3_en/#exchange-information

**Comment by wilianmaique** [comment]
> Could you please implement a support for _exchangeInformation_ endpoint?
> 
> https://mexcdevelop.github.io/apidocs/spot_v3_en/#exchange-information

Good evening, the implementation is simple, as soon as I have some time to spare I'll add it :)

**Comment by wilianmaique** [comment]
added
